FROM ubuntu:19.10

run apt-get update &&  apt-get install -y python3  python3-pip

run pip3 install pyro-ppl
run pip3 install jupyterlab
run pip3 install seaborn 
run pip3 install pandas
run pip3 install sortedcontainers
run pip3 install sklearn


WORKDIR "/root"

CMD [ "jupyter-lab", "--ip", "0.0.0.0", "--port", "8080", "--allow-root" ]